<a href="https://colab.research.google.com/github/Layana7592/Python/blob/main/CatDog_svm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
  `from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
from sklearn.svm import SVC
import numpy as np
import matplotlib.pyplot as plt
import os  #define path of file and directory
from skimage.io import imread  #used for reading images
from sklearn.model_selection import train_test_split
from skimage.transform import resize   #to change the size of image

In [ ]:
os.listdir('/content/drive/MyDrive/Data')

['Cat', 'Dog']

In [ ]:
os.listdir('/content/drive/MyDrive/Data/Cat')

['cat.85.jpg',
 'cat.97.jpg',
 'cat.64.jpg',
 'cat.79.jpg',
 'cat.91.jpg',
 'cat.80.jpg',
 'cat.78.jpg',
 'cat.77.jpg',
 'cat.70.jpg',
 'cat.74.jpg',
 'cat.99.jpg',
 'cat.69.jpg',
 'cat.98.jpg',
 'cat.81.jpg',
 'cat.87.jpg',
 'cat.65.jpg',
 'cat.93.jpg',
 'cat.71.jpg',
 'cat.92.jpg',
 'cat.84.jpg',
 'cat.73.jpg',
 'cat.88.jpg',
 'cat.72.jpg',
 'cat.83.jpg',
 'cat.76.jpg',
 'cat.68.jpg',
 'cat.89.jpg',
 'cat.113.jpg',
 'cat.45.jpg',
 'cat.114.jpg',
 'cat.107.jpg',
 'cat.111.jpg',
 'cat.102.jpg',
 'cat.108.jpg',
 'cat.109.jpg',
 'cat.104.jpg',
 'cat.94.jpg',
 'cat.49.jpg',
 'cat.44.jpg',
 'cat.50.jpg',
 'cat.100.jpg',
 'cat.90.jpg',
 'cat.117.jpg',
 'cat.40.jpg',
 'cat.48.jpg',
 'cat.63.jpg',
 'cat.61.jpg',
 'cat.75.jpg',
 'cat.62.jpg',
 'cat.86.jpg',
 'cat.55.jpg',
 'cat.37.jpg',
 'cat.58.jpg',
 'cat.82.jpg',
 'cat.52.jpg',
 'cat.39.jpg',
 'cat.41.jpg',
 'cat.42.jpg',
 'cat.43.jpg',
 'cat.119.jpg',
 'cat.56.jpg',
 'cat.59.jpg',
 'cat.105.jpg',
 'cat.95.jpg',
 'cat.46.jpg',
 'cat.96.jpg'

In [ ]:
os.listdir('/content/drive/MyDrive/Data/Dog')

['dog.6.jpg',
 'dog.5.jpg',
 'dog.7.jpg',
 'dog.4.jpg',
 'dog.57.jpg',
 'dog.60.jpg',
 'dog.63.jpg',
 'dog.42.jpg',
 'dog.59.jpg',
 'dog.38.jpg',
 'dog.8.jpg',
 'dog.58.jpg',
 'dog.68.jpg',
 'dog.65.jpg',
 'dog.56.jpg',
 'dog.66.jpg',
 'dog.61.jpg',
 'dog.44.jpg',
 'dog.64.jpg',
 'dog.55.jpg',
 'dog.34.jpg',
 'dog.14.jpg',
 'dog.20.jpg',
 'dog.3.jpg',
 'dog.29.jpg',
 'dog.17.jpg',
 'dog.16.jpg',
 'dog.1.jpg',
 'dog.12.jpg',
 'dog.23.jpg',
 'dog.47.jpg',
 'dog.30.jpg',
 'dog.31.jpg',
 'dog.52.jpg',
 'dog.43.jpg',
 'dog.46.jpg',
 'dog.22.jpg',
 'dog.36.jpg',
 'dog.26.jpg',
 'dog.41.jpg',
 'dog.19.jpg',
 'dog.28.jpg',
 'dog.21.jpg',
 'dog.13.jpg',
 'dog.35.jpg',
 'dog.2.jpg',
 'dog.15.jpg',
 'dog.49.jpg',
 'dog.11.jpg',
 'dog.24.jpg',
 'dog.39.jpg',
 'dog.9.jpg',
 'dog.50.jpg',
 'dog.18.jpg',
 'dog.51.jpg',
 'dog.40.jpg',
 'dog.54.jpg',
 'dog.45.jpg',
 'dog.27.jpg',
 'dog.25.jpg',
 'dog.37.jpg',
 'dog.62.jpg',
 'dog.32.jpg',
 'dog.33.jpg',
 'dog.67.jpg',
 'dog.53.jpg',
 'dog.10.jpg',
 'do

In [ ]:
len(os.listdir('/content/drive/MyDrive/Data/Cat'))

85

In [ ]:
len(os.listdir('/content/drive/MyDrive/Data/Dog'))

68

In [ ]:
catpath=os.path.join('/content/drive/MyDrive/Data','Cat')
for img in os.listdir(catpath):
  print(img)

cat.85.jpg
cat.97.jpg
cat.64.jpg
cat.79.jpg
cat.91.jpg
cat.80.jpg
cat.78.jpg
cat.77.jpg
cat.70.jpg
cat.74.jpg
cat.99.jpg
cat.69.jpg
cat.98.jpg
cat.81.jpg
cat.87.jpg
cat.65.jpg
cat.93.jpg
cat.71.jpg
cat.92.jpg
cat.84.jpg
cat.73.jpg
cat.88.jpg
cat.72.jpg
cat.83.jpg
cat.76.jpg
cat.68.jpg
cat.89.jpg
cat.113.jpg
cat.45.jpg
cat.114.jpg
cat.107.jpg
cat.111.jpg
cat.102.jpg
cat.108.jpg
cat.109.jpg
cat.104.jpg
cat.94.jpg
cat.49.jpg
cat.44.jpg
cat.50.jpg
cat.100.jpg
cat.90.jpg
cat.117.jpg
cat.40.jpg
cat.48.jpg
cat.63.jpg
cat.61.jpg
cat.75.jpg
cat.62.jpg
cat.86.jpg
cat.55.jpg
cat.37.jpg
cat.58.jpg
cat.82.jpg
cat.52.jpg
cat.39.jpg
cat.41.jpg
cat.42.jpg
cat.43.jpg
cat.119.jpg
cat.56.jpg
cat.59.jpg
cat.105.jpg
cat.95.jpg
cat.46.jpg
cat.96.jpg
cat.57.jpg
cat.60.jpg
cat.51.jpg
cat.47.jpg
cat.66.jpg
cat.106.jpg
cat.36.jpg
cat.38.jpg
cat.53.jpg
cat.112.jpg
cat.101.jpg
cat.35.jpg
cat.67.jpg
cat.115.jpg
cat.54.jpg
cat.103.jpg
cat.116.jpg
cat.110.jpg
cat.118.jpg


In [ ]:
dogpath=os.path.join('/content/drive/MyDrive/Data','Dog')
for img in os.listdir(dogpath):
  print(img)

dog.6.jpg
dog.5.jpg
dog.7.jpg
dog.4.jpg
dog.57.jpg
dog.60.jpg
dog.63.jpg
dog.42.jpg
dog.59.jpg
dog.38.jpg
dog.8.jpg
dog.58.jpg
dog.68.jpg
dog.65.jpg
dog.56.jpg
dog.66.jpg
dog.61.jpg
dog.44.jpg
dog.64.jpg
dog.55.jpg
dog.34.jpg
dog.14.jpg
dog.20.jpg
dog.3.jpg
dog.29.jpg
dog.17.jpg
dog.16.jpg
dog.1.jpg
dog.12.jpg
dog.23.jpg
dog.47.jpg
dog.30.jpg
dog.31.jpg
dog.52.jpg
dog.43.jpg
dog.46.jpg
dog.22.jpg
dog.36.jpg
dog.26.jpg
dog.41.jpg
dog.19.jpg
dog.28.jpg
dog.21.jpg
dog.13.jpg
dog.35.jpg
dog.2.jpg
dog.15.jpg
dog.49.jpg
dog.11.jpg
dog.24.jpg
dog.39.jpg
dog.9.jpg
dog.50.jpg
dog.18.jpg
dog.51.jpg
dog.40.jpg
dog.54.jpg
dog.45.jpg
dog.27.jpg
dog.25.jpg
dog.37.jpg
dog.62.jpg
dog.32.jpg
dog.33.jpg
dog.67.jpg
dog.53.jpg
dog.10.jpg
dog.48.jpg


In [ ]:
flat_data_arr=[]
target_arr=[]
categories=['Cat','Dog']
datadir='/content/drive/MyDrive/Data'


In [ ]:
for i in categories:
  print("Loading categories........")
  path=os.path.join(datadir,i)
  for img in os.listdir(path):
    img_arr=imread(os.path.join(path,img))
    img_resize=resize(img_arr,(150,150,3))
    flat_data_arr.append(img_resize.flatten())
    target_arr.append(categories.index(i))
  print("Loaded completely",i)


Loading categories........
Loaded completely Cat
Loading categories........
Loaded completely Dog


In [ ]:
flat_data=np.array(flat_data_arr)
target_data=np.array(target_arr)
df=pd.DataFrame(flat_data)
df.shape

(153, 67500)

In [ ]:
df['Target']=target_data

In [ ]:
x=df.iloc[:,:-1]
x

0         1         2         3         4         5         6      \
0    0.274503  0.274503  0.243130  0.230818  0.230818  0.199446  0.207735   
1    0.479761  0.366422  0.326477  0.497796  0.378511  0.336458  0.519553   
2    0.628178  0.526114  0.475343  0.633155  0.530634  0.485047  0.629232   
3    0.992157  0.992157  0.992157  0.992129  0.992129  0.992129  0.989770   
4    0.538843  0.523055  0.478061  0.527895  0.509120  0.483026  0.651962   
..        ...       ...       ...       ...       ...       ...       ...   
148  0.699010  0.691167  0.695088  0.695338  0.687495  0.691417  0.699813   
149  0.567795  0.743022  0.536629  0.576316  0.754119  0.562781  0.532521   
150  0.192608  0.251432  0.278776  0.200281  0.259104  0.286449  0.174399   
151  0.562609  0.466070  0.253184  0.531096  0.417403  0.202458  0.519534   
152  0.294118  0.478431  0.643137  0.294134  0.478448  0.643154  0.296904   

        7         8         9      ...     67490     67491     67492  \
0    0.207735  0.176363  0.203963  ...  0.745575  0.763774  0.731291   
1    0.389613  0.342338  0.524326  ...  0.498604  0.431083  0.458534   
2    0.540237  0.496311  0.654336  ...  0.277512  0.350163  0.288749   
3    0.989770  0.989770  0.988239  ...  0.007752  0.525972  0.317098   
4    0.632398  0.615756  0.625134  ...  0.640268  0.666305  0.646697   
..        ...       ...       ...  ...       ...       ...       ...   
148  0.691969  0.695891  0.710722  ...  0.397026  0.195983  0.274055   
149  0.711565  0.525503  0.521763  ...  0.192060  0.292546  0.214115   
150  0.233223  0.260567  0.174420  ...  0.422395  0.722870  0.683654   
151  0.393667  0.170831  0.488835  ...  0.310426  0.389573  0.366044   
152  0.481218  0.645924  0.299347  ...  0.369032  0.224112  0.262714   

        67493     67494     67495     67496     67497     67498     67499  
0    0.726290  0.726841  0.691690  0.695623  0.737111  0.701817  0.712518  
1    0.521279  0.413828  0.441070  0.503815  0.402136  0.426180  0.488925  
2    0.257374  0.358386  0.283197  0.266701  0.332954  0.272445  0.253367  
3    0.013726  0.560639  0.350321  0.042462  0.559595  0.337547  0.021645  
4    0.634932  0.656431  0.636198  0.624642  0.661928  0.632098  0.623741  
..        ...       ...       ...       ...       ...       ...       ...  
148  0.348877  0.190343  0.271163  0.321875  0.204617  0.279705  0.339664  
149  0.210193  0.233386  0.154954  0.151033  0.266417  0.187986  0.184064  
150  0.546399  0.704635  0.665420  0.528165  0.596154  0.556938  0.419683  
151  0.318985  0.392066  0.368537  0.321478  0.393571  0.370042  0.322983  
152  0.334207  0.289576  0.331113  0.391613  0.174323  0.216358  0.273798  

[153 rows x 67500 columns]

In [ ]:
y=df.iloc[:,-1]
y

0      0
1      0
2      0
3      0
4      0
      ..
148    1
149    1
150    1
151    1
152    1
Name: Target, Length: 153, dtype: int64

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)
x_train

0         1         2         3         4         5         6      \
94   0.883411  0.817155  0.724260  0.807021  0.694468  0.580880  0.833387   
68   0.334195  0.431950  0.362089  0.321361  0.417606  0.347758  0.322483   
22   0.404052  0.415816  0.435424  0.339852  0.351616  0.371224  0.307769   
45   0.303278  0.359850  0.368201  0.360787  0.431970  0.443656  0.289951   
76   0.281699  0.995425  0.999346  0.281699  0.995425  0.999346  0.281699   
..        ...       ...       ...       ...       ...       ...       ...   
71   0.252673  0.225222  0.200269  0.253675  0.226224  0.201271  0.269715   
106  0.328198  0.358391  0.368452  0.325996  0.347217  0.355244  0.370052   
14   0.094118  0.094118  0.086275  0.094118  0.094118  0.086275  0.094118   
92   0.766963  0.763042  0.653238  0.760813  0.756891  0.647087  0.756923   
102  0.420865  0.416943  0.487530  0.404689  0.400768  0.469672  0.417822   

        7         8         9      ...     67490     67491     67492  \
94   0.661539  0.524115  0.847617  ...  0.860142  0.811932  0.811785   
68   0.411826  0.350871  0.320434  ...  0.009716  0.104016  0.077517   
22   0.319534  0.339142  0.287409  ...  0.294440  0.045628  0.083709   
45   0.384418  0.400943  0.231601  ...  0.043252  0.084667  0.084555   
76   0.995425  0.999346  0.281569  ...  0.975382  0.677381  0.997971   
..        ...       ...       ...  ...       ...       ...       ...   
71   0.242264  0.217310  0.277829  ...  0.718447  0.671737  0.695783   
106  0.384387  0.383478  0.383345  ...  0.521430  0.398590  0.420453   
14   0.094118  0.086275  0.094117  ...  0.413832  0.417687  0.416508   
92   0.753001  0.643198  0.753545  ...  0.139000  0.340944  0.249239   
102  0.414203  0.471786  0.410496  ...  0.114466  0.057222  0.178293   

        67493     67494     67495     67496     67497     67498     67499  
94   0.780484  0.790038  0.799478  0.787244  0.772040  0.788076  0.766921  
68   0.039233  0.390348  0.366814  0.305265  0.501509  0.480451  0.410293  
22   0.280102  0.058088  0.081975  0.245260  0.068823  0.074014  0.208115  
45   0.076611  0.132931  0.137470  0.127357  0.141079  0.141287  0.133340  
76   0.993252  0.674711  0.988845  0.975943  0.709319  0.992365  0.986100  
..        ...       ...       ...       ...       ...       ...       ...  
71   0.694567  0.667462  0.687126  0.681188  0.671256  0.689978  0.676960  
106  0.447633  0.448195  0.466741  0.491439  0.532478  0.542804  0.542721  
14   0.406373  0.387455  0.390984  0.381789  0.370306  0.371310  0.369780  
92   0.132068  0.335970  0.244566  0.134054  0.347301  0.268036  0.140000  
102  0.118693  0.052140  0.168848  0.135513  0.054439  0.171995  0.129318  

[122 rows x 67500 columns]

In [ ]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
print("Accuracy_score is",accuracy_score(y_test,y_pred))

Accuracy_score is 0.6129032258064516


In [ ]:
cat_path1='/content/drive/MyDrive/360_F_266724172_Iy8gdKgMa7XmrhYYxLCxyhx6J7070Pr8.jpg'


In [ ]:
img=imread(cat_path1)
img=resize(img,(150,150,3)).flatten().reshape(1,-1)  #input--2D
model.predict(img)

array([0])

In [ ]:
dog_path1='/content/drive/MyDrive/labrador-retriever_1000x.webp'

In [ ]:
img=imread(dog_path1)
img=resize(img,(150,150,3)).flatten().reshape(1,-1)  #input--2D
model.predict(img)

array([0])